#!/bin/sh

path=`ros2 pkg prefix task_manager_client_py`

if which ipython
then
    ipython --no-banner --no-confirm-exit -i $path/lib/task_manager_client_py/console.py -- $*
else 
    ipython3 --no-banner --no-confirm-exit -i $path/lib/task_manager_client_py/console.py -- $*
fi

