//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the task_manager_turtlesim package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __task_manager_turtlesim__TASKGOTOCONFIG_H__
#define __task_manager_turtlesim__TASKGOTOCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace task_manager_turtlesim
{
  class TaskGoToConfigStatics;
  
  class TaskGoToConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(TaskGoToConfig &config, const TaskGoToConfig &max, const TaskGoToConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const TaskGoToConfig &config1, const TaskGoToConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, TaskGoToConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const TaskGoToConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TaskGoToConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const TaskGoToConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T TaskGoToConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (TaskGoToConfig::* field);

      virtual void clamp(TaskGoToConfig &config, const TaskGoToConfig &max, const TaskGoToConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const TaskGoToConfig &config1, const TaskGoToConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, TaskGoToConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const TaskGoToConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TaskGoToConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const TaskGoToConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 12 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      std::string task_rename;
//#line 13 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      bool main_task;
//#line 14 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      double task_period;
//#line 15 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      double task_timeout;
//#line 12 "../cfg/TaskGoTo.cfg"
      double goal_x;
//#line 13 "../cfg/TaskGoTo.cfg"
      double goal_y;
//#line 14 "../cfg/TaskGoTo.cfg"
      double k_v;
//#line 15 "../cfg/TaskGoTo.cfg"
      double k_alpha;
//#line 16 "../cfg/TaskGoTo.cfg"
      double max_velocity;
//#line 17 "../cfg/TaskGoTo.cfg"
      double dist_threshold;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("TaskGoToConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const TaskGoToConfig &__max__ = __getMax__();
      const TaskGoToConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const TaskGoToConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const TaskGoToConfig &__getDefault__();
    static const TaskGoToConfig &__getMax__();
    static const TaskGoToConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const TaskGoToConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void TaskGoToConfig::ParamDescription<std::string>::clamp(TaskGoToConfig &config, const TaskGoToConfig &max, const TaskGoToConfig &min) const
  {
    return;
  }

  class TaskGoToConfigStatics
  {
    friend class TaskGoToConfig;
    
    TaskGoToConfigStatics()
    {
//#line 12 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __min__.task_rename = "";
//#line 12 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __max__.task_rename = "";
//#line 12 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __default__.task_rename = "";
//#line 12 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<std::string>("task_rename", "str", 0, "Task renaming at run-time", "", &TaskGoToConfig::task_rename)));
//#line 13 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __min__.main_task = 0;
//#line 13 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __max__.main_task = 1;
//#line 13 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __default__.main_task = 1;
//#line 13 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<bool>("main_task", "bool", 0, "Task running in foreground", "", &TaskGoToConfig::main_task)));
//#line 14 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __min__.task_period = -std::numeric_limits<double>::infinity();
//#line 14 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __max__.task_period = std::numeric_limits<double>::infinity();
//#line 14 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __default__.task_period = -1.0;
//#line 14 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("task_period", "double", 0, "Task period", "", &TaskGoToConfig::task_period)));
//#line 15 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __min__.task_timeout = -std::numeric_limits<double>::infinity();
//#line 15 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __max__.task_timeout = std::numeric_limits<double>::infinity();
//#line 15 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __default__.task_timeout = -1.0;
//#line 15 "/data/my_ros/ros_task_manager/task_manager_lib/src/task_manager_lib/parameter_generator.py"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("task_timeout", "double", 0, "Task timeout", "", &TaskGoToConfig::task_timeout)));
//#line 12 "../cfg/TaskGoTo.cfg"
      __min__.goal_x = -std::numeric_limits<double>::infinity();
//#line 12 "../cfg/TaskGoTo.cfg"
      __max__.goal_x = std::numeric_limits<double>::infinity();
//#line 12 "../cfg/TaskGoTo.cfg"
      __default__.goal_x = 0.0;
//#line 12 "../cfg/TaskGoTo.cfg"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("goal_x", "double", 0, "X coordinate of destination", "", &TaskGoToConfig::goal_x)));
//#line 13 "../cfg/TaskGoTo.cfg"
      __min__.goal_y = -std::numeric_limits<double>::infinity();
//#line 13 "../cfg/TaskGoTo.cfg"
      __max__.goal_y = std::numeric_limits<double>::infinity();
//#line 13 "../cfg/TaskGoTo.cfg"
      __default__.goal_y = 0.0;
//#line 13 "../cfg/TaskGoTo.cfg"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("goal_y", "double", 0, "Y coordinate of destination", "", &TaskGoToConfig::goal_y)));
//#line 14 "../cfg/TaskGoTo.cfg"
      __min__.k_v = -std::numeric_limits<double>::infinity();
//#line 14 "../cfg/TaskGoTo.cfg"
      __max__.k_v = std::numeric_limits<double>::infinity();
//#line 14 "../cfg/TaskGoTo.cfg"
      __default__.k_v = 1.0;
//#line 14 "../cfg/TaskGoTo.cfg"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("k_v", "double", 0, "Gain for velocity control", "", &TaskGoToConfig::k_v)));
//#line 15 "../cfg/TaskGoTo.cfg"
      __min__.k_alpha = -std::numeric_limits<double>::infinity();
//#line 15 "../cfg/TaskGoTo.cfg"
      __max__.k_alpha = std::numeric_limits<double>::infinity();
//#line 15 "../cfg/TaskGoTo.cfg"
      __default__.k_alpha = 1.0;
//#line 15 "../cfg/TaskGoTo.cfg"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("k_alpha", "double", 0, "Gain for angular control", "", &TaskGoToConfig::k_alpha)));
//#line 16 "../cfg/TaskGoTo.cfg"
      __min__.max_velocity = -std::numeric_limits<double>::infinity();
//#line 16 "../cfg/TaskGoTo.cfg"
      __max__.max_velocity = std::numeric_limits<double>::infinity();
//#line 16 "../cfg/TaskGoTo.cfg"
      __default__.max_velocity = 1.0;
//#line 16 "../cfg/TaskGoTo.cfg"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("max_velocity", "double", 0, "Max allowed velocity", "", &TaskGoToConfig::max_velocity)));
//#line 17 "../cfg/TaskGoTo.cfg"
      __min__.dist_threshold = -std::numeric_limits<double>::infinity();
//#line 17 "../cfg/TaskGoTo.cfg"
      __max__.dist_threshold = std::numeric_limits<double>::infinity();
//#line 17 "../cfg/TaskGoTo.cfg"
      __default__.dist_threshold = 0.1;
//#line 17 "../cfg/TaskGoTo.cfg"
      __param_descriptions__.push_back(TaskGoToConfig::AbstractParamDescriptionConstPtr(new TaskGoToConfig::ParamDescription<double>("dist_threshold", "double", 0, "Distance at which a the target is considered reached", "", &TaskGoToConfig::dist_threshold)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<TaskGoToConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<TaskGoToConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    TaskGoToConfig __max__;
    TaskGoToConfig __min__;
    TaskGoToConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const TaskGoToConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static TaskGoToConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &TaskGoToConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const TaskGoToConfig &TaskGoToConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const TaskGoToConfig &TaskGoToConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const TaskGoToConfig &TaskGoToConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<TaskGoToConfig::AbstractParamDescriptionConstPtr> &TaskGoToConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const TaskGoToConfigStatics *TaskGoToConfig::__get_statics__()
  {
    const static TaskGoToConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = TaskGoToConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __TASKGOTORECONFIGURATOR_H__
