#!/usr/bin/python
# ROS specific imports
import sys

import roslib; 
import rospy


if sys.version[0] == '3':
    from button_server.ButtonServer3 import ButtonServer
else:
    from button_server.ButtonServer2 import ButtonServer

if __name__ == '__main__':
    try:
        server = ButtonServer()
        server.run()
    except rospy.ROSInterruptException: 
        pass

