#!/usr/bin/python3
# ROS specific imports


import sys
from button_server.ButtonServer3 import ButtonServer
import rclpy


if __name__ == '__main__':
    rclpy.init(args=sys.argv)
    server = ButtonServer()
    server.run()
    server.destroy_node()
    rclpy.shutdown()

