#!/usr/bin/python
# ROS specific imports
import roslib; roslib.load_manifest('button_server')
import rospy


import sys
if sys.version[0] == '3':
    from button_server.ButtonServer3 import ButtonServer
else:
    from button_server.ButtonServer2 import ButtonServer

if __name__ == '__main__':
    try:
        server = ButtonServer()
        server.run()
    except rospy.ROSInterruptException: 
        pass

